### ISSUE TITLE
Wordy phrases

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#11]
There is a warning about verbosity in Vale.

Please consider/compare the list we wanted to use in the style checker (issue [#17](https://github.com/SUSE/doc-styleguide/issues/17), [#120](https://github.com/SUSE/doc-styleguide/issues/120))

actually → (delete)
as necessary → (delete)
in fact → (delete)
if you want to → to
in order to → to
in order for → for
(as) of late → lately
as per → per
as a means of → to
as long as → if
as to whether → whether
at a slow rate → slowly
at a quick rate → quickly
a majority of → most
a number of → some, a few, several
in accordance with → by, per, under
do damage to → damage
during the course of → during
in the course of → during, in, over, or while
for the duration of → during, through, for, or throughout
for the purpose(s) of → wordy for to or for
in terms of → regarding
make an effort → try
in an effort to → to
(the) majority of → most
previous to → before
prior to → before
take into consideration → consider
with the exception of → except (for), apart (from)
in the event that → if
have an impact on → affect, influence
have an effect on → affect, influence
the way in which → how
in a similar manner → similarly
give the opportunity to → let, allow
provide the ability to → let, allow
are representative of → represent
by means of → by, via
by the use of → using, with
by virtue of → because
by way of → by, via
in excess of → more than, over
in the absence of → without
as far as [X] is concerned → regarding
at the present time → now, currently
as of this writing → now, currently
at the time of publication → now, currently
at the current time → now, currently
at this point in time → now, currently
due to the fact that → because, since
despite the fact that → though, even though
be aware of the fact that → know, understand
in light of the fact that → because, considering
it’s important to note that → notably
in the direction of → toward
make a choice → choose, decide
(are) indicative of → reveal, show, suggest
on account of → because

Redundant phrases
still remain → remain
retain the same → retain
minor tweaks → tweaks
end result → result
both of them → both
trailing behind → trailing
factor that plays a role → factor
tailored to fit → tailored
specific details → details
check and see → check
good-quality (adj.) → quality
notification alert → notification (or alert)
in close proximity to → close to, near
debut of a new product → product debut
a little bit → a bit (or a little)

Unnecessary prepositions
click on → click
tap on → tap
raise up → raise
help out → help
last for [length of time] → last [length of time]
add together → add
send out → send

**Comment by dmpop** [comment]
I'll add a separate filter for these entries. I'd have to skip some of the entries, though, because they cannot be defined as Vale rules.
