### ISSUE TITLE
manpage does not display error 

### ISSUE THREAD

**Issue by Amrita42** [openSUSE/suse-vale-styleguide#113]
Not sure if its only me , but in vs code , manpage , does not display a hover error message.

**Comment by alexvonme** [comment]
Do other rules work? Under the current style guide, ``Terms.yml`` should have suggested a correction for it.

I tested the rule on my system and ``manpage`` is highlighted as an error while ``man page`` is the suggested correction.

**Comment by alexvonme** [comment]
@tbazant there haven't been any updates to this one. Presumably, the issue was resolved. I'd suggest closing this issue.
