### ISSUE TITLE
Update the use of commas in simple series

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#19]
Hi Dima,

Please update the rule for the use of commas and punctuation in quotations marks per the newly released style guide. Please see [here](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-comma) and [here](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-quotation).

Thanks!

**Comment by tbazant** [comment]
@dmpop this issue boils down to the folloing rules:

- when `'` or `"` string is found wrapping a word or sentence, suggest using `<quote/>`
- when there is a `,` or `.` after `'` or `"`, or `</quote>`, suggest inserting it into `<quote/>`
- when `:` or `;` or` -` is inside `<quote/>`, suggest moving it outside of `<quote/>`
- for simple series ("one, two, or three"), suggest to remove the last `,`
