### ISSUE TITLE
Oxford comma advice is contradictory

### ISSUE THREAD

**Issue by tahliar** [openSUSE/suse-vale-styleguide#26]
For example, the sentence "Through this daemon, Pacemaker can start, stop, and monitor resources." in `ha_glossary.xml` in `doc-sleha`. 

_With_ the Oxford comma, Vale tells me `Simple series, consider removing the last comma`. When I _remove_ the comma, Vale switches to telling me `Use the serial (Oxford) comma`. So it's mad at me no matter what I do. 

Personally, I prefer the Oxford comma, but I know not everyone agrees.

**Comment by tbazant** [comment]
fixed by https://github.com/openSUSE/suse-vale-styleguide/commit/93a5a71f85a7c9ff3ceeb14491e3b97689b481c7
