### ISSUE TITLE
The first word after colon should be in lowercase

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#36]
There is an admonition to not capitalize the word following the colon, which is correct (Colons.yml).
But there is an exception. When it is a full sentence, it should be capitalized. 
See the [SUSE Style Guide](https://mysuse.sharepoint.com/sites/SUSEStyleandWritersGuide#colon) for colons.

**Comment by tbazant** [comment]
@dariavladykina how do i recognize a whole sentence? That it ends with a period?

**Comment by tbazant** [comment]
fixed by https://github.com/openSUSE/suse-vale-styleguide/commit/532153dc64bdfe9c7f54ba7ac35828b7eb5fab5f
