### ISSUE TITLE
Conflicting rules for serial comma

### ISSUE THREAD

**Issue by sounix000** [openSUSE/suse-vale-styleguide#62]
Observation on our Vale rules:
The SerialComma.yml rule for Oxford serial comma, and the SimpleSeries.yml rule seems to offer conflicting suggestions about using comma. At least that is my experience when using the Vale extension for VS Code.

A duplicate of this issue is here: https://github.com/openSUSE/vscode-suse-vale-styleguide/issues/3#issue-1798884321. Please close one of them, as appropriate.

**Comment by dariavladykina** [comment]
I thought that #21 and #38 have already solved that.

**Comment by tbazant** [comment]
i thought SerialComma.yml was removed weeks ago, check your setup pls
