### ISSUE TITLE
'hotplugging' is correct according to StyleGuide, why Termweb doscourages it?

### ISSUE THREAD

**Issue by tbazant** [openSUSE/suse-vale-styleguide#72]
![obrazek](https://github.com/openSUSE/suse-vale-styleguide/assets/2240174/f8a93bed-8975-4f9c-98b4-3c92436fb07c)

@jfaltenbacher why is that?^^^

**Comment by dariavladykina** [comment]
My guess is that it could discourage 'hotswapping' in favor of 'hotplugging' when hotswapping is used. TermWeb advises to use these terms in different use cases, but is the engine so smart to distinguish? :-)

**Comment by jfaltenbacher** [comment]
yes, Daria is right. depending on the context either one can be right or forbidden:
hotpluggig is commonly used for non-RAID devices. For RAID devices, use hotswapping.
