### ISSUE TITLE
Warning for 'here' at all times 

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#82]
It seems that 'here' is brought up in alert every time Vale sees it. It is supposed to warn against using 'here' as the content of the link but I can see the warning in all occurrences:

![image](https://github.com/openSUSE/suse-vale-styleguide/assets/98878014/4364815c-590a-46bb-b709-9bbfd06c8c93)

**Comment by tbazant** [comment]
fixed by https://github.com/openSUSE/suse-vale-styleguide/commit/19655a98b9f436bd83534be8f948a8e23a4928cf
