### ISSUE TITLE
NVIDIA spelling

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#83]
NVIDIA must be all caps according to its [official documentation](https://www.nvidia.com/en-us/). For some reason, Vale has it otherwise.
Also see here: https://github.com/SUSE/doc-styleguide/issues/23
![image](https://github.com/openSUSE/suse-vale-styleguide/assets/98878014/69025ef4-a71d-4706-aed1-096be566b464)

**Comment by tbazant** [comment]
fixed by https://github.com/openSUSE/suse-vale-styleguide/commit/f60c5914554429570806bd4b5d2bb87cfd3d0237
