### ISSUE TITLE
"unit file" is not recognized correctly

### ISSUE THREAD

**Issue by dmpop** [openSUSE/suse-vale-styleguide#85]
The screenshot is self-explanatory. :smile: 

![Screenshot_20240425_110925](https://github.com/openSUSE/suse-vale-styleguide/assets/837588/a24c0063-b4cf-4f6c-84b7-cd02bb95e763)

**Comment by tbazant** [comment]
I cant reproduce it, `unit file` is not covered by Vale styles at all
