### ISSUE TITLE
"in this case" false positive

### ISSUE THREAD

**Issue by dmpop** [openSUSE/suse-vale-styleguide#86]
![Screenshot_20240425_113055](https://github.com/openSUSE/suse-vale-styleguide/assets/837588/2a4a3d78-412c-4585-9f10-f180f10bafb2)

**Comment by tbazant** [comment]
solved by https://github.com/openSUSE/suse-vale-styleguide/commit/7354e7303790a4b8da3ae14e824eb5757fd916ba
