### ISSUE TITLE
False positive for 'hotplug'

### ISSUE THREAD

**Issue by dariavladykina** [openSUSE/suse-vale-styleguide#87]
TermWeb instructs on different use cases for 'hotplug' and 'hotswap' (and there are some regex for them), but for some reason Vale instructs against using 'hotplug', 'hotplugged' in favor of 'hot plug' and 'hot plugged'.

**Comment by tbazant** [comment]
i cant reproduce this
![obrazek](https://github.com/openSUSE/suse-vale-styleguide/assets/2240174/52ff7f90-444d-430c-9323-210fac26e038)

**Comment by dariavladykina** [comment]
Indeed, I also can't reproduce now. It only says "hotplugging" and other derivatives are unknown.
